version: '2.1'
services:
    untube-proxy:
      image: baangaritar/1e-videos-proxy
      depends_on:
        - untube-api
      ports:
        - "80:80"
    untube-api:
      image: baangaritar/1e-videos-api-gateway
      environment:
        PORT: '5000'
        SHOW_URLS: 'true'

        USERS_ENTRY: 'auth'
        USERS_PORT: '3000'
        USERS_URL: '35.196.3.185'
      
        RECOMMENDATIONS_ENTRY: 'recommendations'
        RECOMMENDATIONS_PORT: '3003'
        RECOMMENDATIONS_URL: '35.196.3.185'
      
        COMMENTARIES_ENTRY: 'feedback/resources/commentaries'
        COMMENTARIES_PORT: '3004'
        COMMENTARIES_URL: '35.196.3.185'

    feedback-db:
      image: mysql:5.7
      ports:
        - 3308:3308
      environment:
        MYSQL_DATABASE: feedback-db
        MYSQL_PASSWORD: '123'
        MYSQL_ROOT_PASSWORD: '123'
        MYSQL_USER: sa
        MYSQL_HOST: feedback-db
  
    users-db:
      image: mysql:5.7
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_USER: arquisoft
        MYSQL_PASSWORD: 123
        MYSQL_DATABASE: auth
        MYSQL_HOST: users-db
  
    recommendations-db:
      image: postgres

    users-ms:
      image: baangaritar/1e-videos-user-ms
      environment:
        PORT: '3000'
      depends_on:
        - 'users-db'

    
    recommendations-ms:
      image: baangaritar/1e-videos-recommendations-ms
      environment:
        PORT: '3003'
      depends_on:
        - recommendations-db
    
    feedback-ms:
      image: baangaritar/1e-videos-feedback-ms
      environment:
        PORT: '3004'
      depends_on:
        - 'feedback-db'
     
